"""Add wrong_count to learning_logs

Revision ID: 86dd0fb98bbe
Revises: e42ad4eb0079
Create Date: 2026-08-05 14:09:11.314657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86dd0fb98bbe'
down_revision = 'e42ad4eb0079'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wrong_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_logs', schema=None) as batch_op:
        batch_op.drop_column('wrong_count')

    # ### end Alembic commands ###
