"""add learning_logs table

Revision ID: e42ad4eb0079
Revises: 98ebb14874d1
Create Date: 2026-08-05 12:01:21.707752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e42ad4eb0079'
down_revision = '98ebb14874d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('word_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('choice', sa.String(length=20), nullable=True),
    sa.Column('level_before', sa.Integer(), nullable=True),
    sa.Column('level_after', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learning_logs', schema=None) as batch_op:
        batch_op.create_index('idx_learning_logs_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index('idx_learning_logs_user_word', ['user_id', 'word_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_learning_logs_user_word')
        batch_op.drop_index('idx_learning_logs_user_created')

    op.drop_table('learning_logs')
    # ### end Alembic commands ###
